Repository KittyCAD/modeling-app, pull requests merged in 2023-12, with the labels that each got.

#1167 expand lsp test
  e2e/playwright/flow-tests.spec.ts
Labels: e2e

#1184 Prepare command bar to support modeling commands
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/change-camera-show-planes-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/change-camera-show-planes-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/change-camera-show-planes-3-Google-Chrome-linux.png
  public/Icon/Icon/Projects/Create File.svg
  public/Icon/Icon/Projects/Create Folder.svg
  public/Icon/Icon/Projects/File.svg
  src/Toolbar.module.css
  src/Toolbar.tsx
  src/components/ActionButton.tsx
  src/components/ActionIcon.tsx
  src/components/AppHeader.tsx
  src/components/CodeMenu.module.css
  src/components/CodeMenu.tsx
  src/components/CollapsiblePanel.tsx
  src/components/CommandBar.tsx
  src/components/CustomIcon.tsx
  src/components/DownloadAppBanner.tsx
  src/components/ExportButton.tsx
  src/components/FileTree.tsx
  src/components/GlobalStateProvider.tsx
  src/components/NetworkHealthIndicator.test.tsx
  src/components/NetworkHealthIndicator.tsx
  src/components/ProjectCard.tsx
  src/components/ProjectSidebarMenu.tsx
  src/components/UserSidebarMenu.tsx
  src/components/WasmErrBanner.tsx
  src/hooks/useStateMachineCommands.ts
  src/index.css
  src/index.tsx
  src/lib/commands.ts
  src/lib/sorting.ts
  src/machines/authMachine.ts
  src/machines/homeMachine.ts
  src/machines/settingsMachine.ts
  src/routes/Home.tsx
  src/routes/Onboarding/Camera.tsx
  src/routes/Onboarding/CmdK.tsx
  src/routes/Onboarding/CodeEditor.tsx
  src/routes/Onboarding/Export.tsx
  src/routes/Onboarding/FutureWork.tsx
  src/routes/Onboarding/InteractiveNumbers.tsx
  src/routes/Onboarding/Introduction.tsx
  src/routes/Onboarding/ParametricModeling.tsx
  src/routes/Onboarding/ProjectMenu.tsx
  src/routes/Onboarding/Sketching.tsx
  src/routes/Onboarding/Streaming.tsx
  src/routes/Onboarding/UserMenu.tsx
  src/routes/Onboarding/index.tsx
  src/routes/Settings.tsx
  tailwind.config.js
Labels: refactor

#1204 Command bar: add extrude command, nonlinear editing, etc
  e2e/playwright/export-snapshots/gltf-binary.gltf
  e2e/playwright/export-snapshots/gltf-embedded.gltf
  e2e/playwright/export-snapshots/gltf-standard-2.gltf
  e2e/playwright/export-snapshots/ply-ascii.ply
  e2e/playwright/export-snapshots/ply-binary_big_endian.ply
  e2e/playwright/export-snapshots/ply-binary_little_endian.ply
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/change-camera-show-planes-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/change-camera-show-planes-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/change-camera-show-planes-3-Google-Chrome-linux.png
  src/App.test.tsx
  src/Router.tsx
  src/Toolbar.tsx
  src/components/AppHeader.tsx
  src/components/CollapsiblePanel.tsx
  src/components/CommandBar.tsx
  src/components/CommandBar/CommandArgOptionInput.tsx
  src/components/CommandBar/CommandBar.tsx
  src/components/CommandBar/CommandBarArgument.tsx
  src/components/CommandBar/CommandBarBasicInput.tsx
  src/components/CommandBar/CommandBarHeader.tsx
  src/components/CommandBar/CommandBarReview.tsx
  src/components/CommandBar/CommandBarSelectionInput.tsx
  src/components/CommandComboBox.tsx
  src/components/CustomIcon.tsx
  src/components/FileMachineProvider.tsx
  src/components/GlobalStateProvider.tsx
  src/components/Loading.tsx
  src/components/ModelingMachineProvider.tsx
  src/components/NetworkHealthIndicator.test.tsx
  src/components/NetworkHealthIndicator.tsx
  src/components/ProjectCard.tsx
  src/components/ProjectSidebarMenu.test.tsx
  src/components/Stream.tsx
  src/components/TextEditor.tsx
  src/components/UserSidebarMenu.test.tsx
  src/hooks/useCommandsContext.ts
  src/hooks/usePlatform.ts
  src/hooks/useStateMachineCommands.ts
  src/index.css
  src/lang/modifyAst.ts
  src/lib/commandBarConfigs/authCommandConfig.ts
  src/lib/commandBarConfigs/homeCommandConfig.ts
  src/lib/commandBarConfigs/modelingCommandConfig.ts
  src/lib/commandBarConfigs/settingsCommandConfig.ts
  src/lib/commandTypes.ts
  src/lib/commands.ts
  src/lib/createMachineCommand.ts
  src/lib/selections.ts
  src/machines/authMachine.ts
  src/machines/commandBarMachine.ts
  src/machines/commandBarMachine.typegen.ts
  src/machines/homeMachine.ts
  src/machines/modelingMachine.ts
  src/machines/modelingMachine.typegen.ts
  src/machines/settingsMachine.ts
  src/routes/Home.tsx
  src/routes/Onboarding/CmdK.tsx
  src/routes/SignIn.tsx
  yarn.lock
Labels: enhancement, refactor
