Repository KittyCAD/modeling-app, pull requests merged in 2024-06, with the labels that each got.

#2549 Update code mods for extrude so that new top-level constants are created
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Inch-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Inch-scale-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Millimeter-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Millimeter-scale-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-rectangles-should-look-right-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Sketch-on-face-with-none-z-up-1-Google-Chrome-linux.png
  src/clientSideScene/sceneEntities.ts
  src/components/ModelingMachineProvider.tsx
  src/lang/modifyAst.test.ts
  src/lang/modifyAst.ts
  src/lang/std/engineConnection.ts
  src/lib/constants.ts
  src/machines/modelingMachine.ts
Labels: ast, kcl, sketch

#2581 Prevent Firefox's global paste behavior if paste target is not also focused
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/test-utils.ts
  playwright.config.ts
  src/components/Stream.tsx
Labels: ux papercut

#2604 cache playwright browsers
  .github/workflows/playwright.yml
Labels: e2e

#2623 Remove debug logging from Engine Connection
  src/lang/std/engineConnection.ts
Labels: dev

#2700 Retain sketch selection segment color after adding a constraint to the segment
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/test-utils.ts
  src/clientSideScene/sceneEntities.ts
  src/clientSideScene/segments.ts
  src/lib/selections.ts
  src/machines/modelingMachine.ts
Labels: ux papercut, sketch

#2783 Call core dump from the bug reporting button(s)
  src-tauri/Cargo.lock
  src/App.tsx
  src/components/LowerRightControls.tsx
  src/components/ModelingMachineProvider.tsx
  src/components/RefreshButton.tsx
  src/lang/wasm.ts
  src/lib/coredump.ts
Labels: enhancement
