Repository KittyCAD/modeling-app, pull requests merged in 2024-05, with the labels that each got.

#2306 Exit edit mode when selection input is up, re-enter when it's not.
  src/components/CommandBar/CommandBarSelectionInput.tsx
Labels: bug

#2313 Make "Extrude from command bar" test selection via 3D scene, not code
  e2e/playwright/flow-tests.spec.ts
Labels: tests

#2317 Move the command bar out to the right in the AppHeader
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Inch-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Inch-scale-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Millimeter-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Millimeter-scale-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-rectangles-should-look-right-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Sketch-on-face-with-none-z-up-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--XY-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--XZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--YZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-XY-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-XZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-YZ-1-Google-Chrome-linux.png
  src/Toolbar.tsx
  src/components/AppHeader.tsx
  src/components/CommandBarOpenButton.tsx
  src/components/CommandComboBox.tsx
Labels: design

#2328 Franknoirot/sketch light mode
  src/clientSideScene/ClientSideSceneComp.tsx
  src/clientSideScene/sceneEntities.ts
  src/clientSideScene/sceneInfra.ts
  src/clientSideScene/segments.ts
  src/components/SettingsAuthProvider.tsx
  src/lib/theme.ts
  src/machines/settingsMachine.ts
Labels: design

#2327 Add a component for toolbar buttons with a dropdown, consolidate Constrain actions under one
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Inch-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Inch-scale-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Millimeter-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Millimeter-scale-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-rectangles-should-look-right-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Sketch-on-face-with-none-z-up-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--XY-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--XZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--YZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-XY-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-XZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-YZ-1-Google-Chrome-linux.png
  src/Toolbar.tsx
  src/components/ActionButton.tsx
  src/components/ActionButtonDropdown.tsx
  src/components/ActionIcon.tsx
  src/components/CommandBar/CommandBarHeader.tsx
  src/components/CustomIcon.tsx
  src/components/DownloadAppBanner.tsx
  src/components/ErrorPage.tsx
  src/components/FileTree.tsx
  src/components/ProjectCard.tsx
  src/components/ProjectSidebarMenu.tsx
  src/components/SetVarNameModal.tsx
  src/components/UpdaterModal.tsx
  src/components/UpdaterRestartModal.tsx
  src/components/UserSidebarMenu.tsx
  src/components/WasmErrBanner.tsx
  src/routes/Home.tsx
  src/routes/Onboarding/Units.tsx
  src/routes/Onboarding/index.tsx
  src/routes/Settings.tsx
  src/routes/SignIn.tsx
Labels: design

#2324 Ensure that onboarding buttons are visible, even on short viewports
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-YZ-1-Google-Chrome-linux.png
  src/routes/Onboarding/CodeEditor.tsx
  src/routes/Onboarding/InteractiveNumbers.tsx
  src/routes/Onboarding/ParametricModeling.tsx
  src/routes/Onboarding/Streaming.tsx
  src/routes/Onboarding/index.tsx
Labels: bug, design

#2348 Fix settings overflow by setting grid-template-rows
  src-tauri/Cargo.lock
  src/routes/Settings.tsx
Labels: bug, design

#2375 Fix CSS bug causing ProjectCard links to flicker
  src/components/ProjectCard.tsx
Labels: bug, ux papercut

#2372 Disable all pane resize handles except right
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Inch-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Millimeter-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-rectangles-should-look-right-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-2-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Sketch-on-face-with-none-z-up-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--XY-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--XZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--YZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-XY-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-XZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-YZ-1-Google-Chrome-linux.png
  src/components/ModelingSidebar/ModelingSidebar.tsx
Labels: bug

#2371 Disable home logo link in the browser app
  e2e/playwright/flow-tests.spec.ts
  src/components/AppHeader.tsx
  src/components/ProjectSidebarMenu.test.tsx
  src/components/ProjectSidebarMenu.tsx
Labels: bug

#2373 Add stdlib functions for getting sketch profile start and its components
  README.md
  docs/kcl/index.md
  docs/kcl/profileStart.md
  docs/kcl/profileStartX.md
  docs/kcl/profileStartY.md
  docs/kcl/std.json
  e2e/playwright/flow-tests.spec.ts
  src/wasm-lib/kcl/README.md
  src/wasm-lib/kcl/src/std/mod.rs
  src/wasm-lib/kcl/src/std/sketch.rs
  src/wasm-lib/kcl/tests/outputs/serial_test_example_profile_start0.png
  src/wasm-lib/kcl/tests/outputs/serial_test_example_profile_start_x0.png
  src/wasm-lib/kcl/tests/outputs/serial_test_example_profile_start_y0.png
Labels: kcl

#2419 Add keyboard shortcuts for sketch and modeling tools
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Inch-scale-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Client-side-scene-scale-should-match-engine-scale-Millimeter-scale-1-Google-Chrome-linux.png
  src/App.tsx
  src/Toolbar.tsx
  src/components/ModelingMachineProvider.tsx
Labels: ux papercut

#2489 Update point-and-click sketch close code generation to use explicit lines
  e2e/playwright/flow-tests.spec.ts
  src/clientSideScene/sceneEntities.ts
  src/lang/std/sketch.ts
Labels: ux papercut

#2496 Allow any value to start a pipe expression
  src/wasm-lib/kcl/src/ast/types.rs
  src/wasm-lib/tests/executor/inputs/pipe_as_arg.kcl
Labels: kcl

#2541 Add a promise-based toast when exporting
  e2e/playwright/flow-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts
  e2e/playwright/test-utils.ts
  src-tauri/Cargo.lock
  src/components/ModelingMachineProvider.tsx
  src/lang/std/engineConnection.ts
Labels: enhancement

#2565 Update rectangle code gen to use `profileStart` to close shape
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-rectangles-should-look-right-1-Google-Chrome-linux.png
  src/lib/rectangleTool.ts
Labels: ux papercut, sketch
