Repository KittyCAD/modeling-app, pull requests merged in 2024-09, with the labels that each got.

#3823 Get playwright green
  e2e/playwright/file-tree.spec.ts
  e2e/playwright/test-utils.ts
  e2e/playwright/testing-settings.spec.ts
  e2e/playwright/text-to-cad-tests.spec.ts
Labels: tests

#3867 Remove most of modelingMachine.context.store
  e2e/playwright/testing-camera-movement.spec.ts
  e2e/playwright/testing-selections.spec.ts
  src/App.tsx
  src/clientSideScene/CameraControls.ts
  src/clientSideScene/sceneInfra.ts
  src/components/ModelingSidebar/ModelingPane.tsx
  src/components/ModelingSidebar/ModelingSidebar.tsx
  src/components/Stream.tsx
  src/hooks/useSetupEngineManager.ts
  src/lib/selections.ts
  src/machines/modelingMachine.ts
  src/routes/Onboarding/Camera.tsx
  src/routes/Onboarding/CmdK.tsx
  src/routes/Onboarding/CodeEditor.tsx
  src/routes/Onboarding/Export.tsx
  src/routes/Onboarding/InteractiveNumbers.tsx
  src/routes/Onboarding/ParametricModeling.tsx
  src/routes/Onboarding/ProjectMenu.tsx
  src/routes/Onboarding/Sketching.tsx
  src/routes/Onboarding/Streaming.tsx
  src/routes/Onboarding/UserMenu.tsx
Labels: refactor

#3884 Fix canExtrudeSelectionItem and getSelectionType for multiple selections
  src/lib/selections.ts
Labels: desktop-app, polish

#3719 Add tests that verify folder deletion behavior
  e2e/playwright/file-tree.spec.ts
  e2e/playwright/projects.spec.ts
Labels: tests

#3927 Add a test step to confirm the solid bg of the settings dialog
  e2e/playwright/testing-settings.spec.ts
Labels: tests
