Repository KittyCAD/modeling-app, pull requests merged in 2025-02, with the labels that each got.

#5098 Add Point-and-Click Deletion for Fillets and Chamfers
  e2e/playwright/point-click.spec.ts
  src/lang/modifyAst.ts
  src/lang/modifyAst/addEdgeTreatment.test.ts
  src/lang/modifyAst/addEdgeTreatment.ts
Labels: ast

#5243 Refactor Edge Treatment Module to Break Cyclic Dependency
  src/lang/modifyAst/addEdgeTreatment.test.ts
  src/lang/modifyAst/addEdgeTreatment.ts
  src/lang/modifyAst/addShell.ts
  src/machines/modelingMachine.ts
Labels: bug

#5289 Fix Shift-Click to Deselect Edges/Faces
  e2e/playwright/point-click.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--YZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-XY-1-Google-Chrome-linux.png
  src/components/ModelingMachineProvider.tsx
Labels: bug, dev, desktop-app

#5142 [Refactor] decouple settingsMachine from React
  e2e/playwright/onboarding-tests.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Grid-visibility-Grid-turned-off-to-on-via-command-bar-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Sketch-on-face-with-none-z-up-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Zoom-to-fit-on-load---solid-2d-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/code-color-goober-code-color-goober-opening-window-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--XZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--YZ-1-Google-Chrome-linux.png
  e2e/playwright/testing-camera-movement.spec.ts
  e2e/playwright/testing-settings.spec.ts
  src/App.tsx
  src/Router.tsx
  src/clientSideScene/ClientSideSceneComp.tsx
  src/components/CameraProjectionToggle.tsx
  src/components/CommandBar/CommandBarKclInput.tsx
  src/components/DownloadAppBanner.tsx
  src/components/FileMachineProvider.tsx
  src/components/HelpMenu.tsx
  src/components/LspProvider.tsx
  src/components/ModelingMachineProvider.tsx
  src/components/ModelingSidebar/ModelingPane.tsx
  src/components/ModelingSidebar/ModelingPanes/KclEditorPane.tsx
  src/components/ModelingSidebar/ModelingSidebar.tsx
  src/components/NetworkHealthIndicator.test.tsx
  src/components/ProjectSidebarMenu.test.tsx
  src/components/ProjectSidebarMenu.tsx
  src/components/ProjectsContextProvider.tsx
  src/components/RefreshButton.tsx
  src/components/RouteProvider.tsx
  src/components/Settings/AllSettingsFields.tsx
  src/components/Settings/SettingsFieldInput.tsx
  src/components/Settings/SettingsSearchBar.tsx
  src/components/Settings/SettingsSectionsList.tsx
  src/components/SettingsAuthProvider.tsx
  src/components/Stream.tsx
  src/components/UnitsMenu.tsx
  src/components/UserSidebarMenu.test.tsx
  src/hooks/useCreateFileLinkQueryWatcher.ts
  src/hooks/useRefreshSettings.ts
  src/hooks/useResolvedTheme.ts
  src/hooks/useSettingsAuthContext.ts
  src/index.tsx
  src/lang/KclProvider.tsx
  src/lang/wasm.ts
  src/lib/commandBarConfigs/settingsCommandConfig.ts
  src/lib/desktop.ts
  src/lib/paths.ts
  src/lib/routeLoaders.ts
  src/lib/settings/initialSettings.tsx
  src/lib/settings/settingsUtils.ts
  src/machines/appMachine.ts
  src/machines/authMachine.ts
  src/machines/machineConstants.ts
  src/machines/settingsMachine.ts
  src/routes/Home.tsx
  src/routes/Onboarding/Camera.tsx
  src/routes/Onboarding/Introduction.tsx
  src/routes/Onboarding/ParametricModeling.tsx
  src/routes/Onboarding/Units.tsx
  src/routes/Onboarding/index.tsx
  src/routes/SignIn.tsx
Labels: refactor

#5456 Fix Second-Body Extrude Selection
  src/lang/modifyAst/addEdgeTreatment.test.ts
  src/lang/modifyAst/addEdgeTreatment.ts
  src/lang/modifyAst/addShell.ts
  src/lang/std/artifactGraph.ts
  src/machines/modelingMachine.ts
Labels: bug
