Repository KittyCAD/modeling-app, pull requests merged in 2025-04, with the labels that each got.

#6091 Display the next version using native git commands
  scripts/semantic-release.sh
Labels: dev

#6077 Remove the camera projection toggle from the UI
  e2e/playwright/storageStates.ts
  e2e/playwright/testing-gizmo.spec.ts
  e2e/playwright/testing-perspective-toggle.spec.ts
  src/App.tsx
Labels: design

#6207 Handle PowerShell vs. Git Bash on Windows
  Makefile
Labels: dev

#6233 Add a sidebar action to create a share link
  src/components/ModelingSidebar/ModelingSidebar.tsx
Labels: ux-papercut
