Repository KittyCAD/modeling-app, pull requests merged in 2025-01, with the labels that each got.

#4694 Hook up chamfer UI with AST-mod
  e2e/playwright/fixtures/toolbarFixture.ts
  e2e/playwright/point-click.spec.ts
  src/lib/commandBarConfigs/modelingCommandConfig.ts
  src/lib/toolbar.ts
  src/machines/modelingMachine.ts
Labels: feature, tests

#5009 Remove Redundant Fillet Button State Test
  e2e/playwright/testing-selections.spec.ts
Labels: tests

#4909 Refactor Fillet Playwright Test to the new Fixture-based Approach
  e2e/playwright/command-bar-tests.spec.ts
  e2e/playwright/fixtures/toolbarFixture.ts
  e2e/playwright/point-click.spec.ts
Labels: refactor, tests

#5108 Refactor: decouple command palette actor from React
  src/Router.tsx
  src/Toolbar.tsx
  src/clientSideScene/ClientSideSceneComp.tsx
  src/clientSideScene/segments.ts
  src/components/CommandBar/CommandArgOptionInput.tsx
  src/components/CommandBar/CommandBar.tsx
  src/components/CommandBar/CommandBarArgument.tsx
  src/components/CommandBar/CommandBarBasicInput.tsx
  src/components/CommandBar/CommandBarHeader.tsx
  src/components/CommandBar/CommandBarKclInput.tsx
  src/components/CommandBar/CommandBarProvider.tsx
  src/components/CommandBar/CommandBarReview.tsx
  src/components/CommandBar/CommandBarSelectionInput.tsx
  src/components/CommandBar/CommandBarTextareaInput.tsx
  src/components/CommandBarOpenButton.tsx
  src/components/CommandComboBox.tsx
  src/components/FileMachineProvider.tsx
  src/components/MachineManagerProvider.tsx
  src/components/ModelingMachineProvider.tsx
  src/components/ModelingSidebar/ModelingPanes/KclEditorMenu.tsx
  src/components/ModelingSidebar/ModelingSidebar.tsx
  src/components/NetworkHealthIndicator.test.tsx
  src/components/ProjectSidebarMenu.test.tsx
  src/components/ProjectSidebarMenu.tsx
  src/components/ProjectsContextProvider.tsx
  src/components/SettingsAuthProvider.tsx
  src/components/Stream.tsx
  src/components/ToastTextToCad.tsx
  src/components/UserSidebarMenu.test.tsx
  src/editor/manager.ts
  src/hooks/useCommandsContext.ts
  src/hooks/useStateMachineCommands.ts
  src/lib/textToCad.ts
  src/lib/toolbar.ts
  src/machines/commandBarMachine.ts
  src/routes/Home.tsx
Labels: refactor

#5139 Refactor getNodePathFromSourceRange
  e2e/playwright/snapshot-tests.spec.ts-snapshots/code-color-goober-code-color-goober-1-Google-Chrome-linux.png
  src/clientSideScene/sceneEntities.ts
  src/components/AstExplorer.tsx
  src/components/ModelingMachineProvider.tsx
  src/components/Toolbar/EqualAngle.tsx
  src/hooks/useEngineConnectionSubscriptions.ts
  src/lang/getNodePathFromSourceRange.test.ts
  src/lang/modifyAst.test.ts
  src/lang/modifyAst.ts
  src/lang/modifyAst/addEdgeTreatment.test.ts
  src/lang/modifyAst/addEdgeTreatment.ts
  src/lang/modifyAst/addRevolve.ts
  src/lang/queryAst.test.ts
  src/lang/queryAst.ts
  src/lang/queryAstNodePathUtils.ts
  src/lang/std/artifactGraph.ts
  src/lang/std/sketch.test.ts
  src/lang/std/sketch.ts
  src/lang/std/sketchcombos.ts
  src/lang/wasm.ts
  src/lib/selections.ts
  src/machines/modelingMachine.ts
Labels: bug

#5176 Bug fix: open project command lists project names
  e2e/playwright/fixtures/cmdBarFixture.ts
  e2e/playwright/projects.spec.ts
  src/components/CommandBar/CommandBar.tsx
  src/lib/commandBarConfigs/projectsCommandConfig.ts
Labels: bug

#5146 Migrate Extrude AST mod from XState action to actor
  src/machines/modelingMachine.ts
Labels: refactor
