Repository KittyCAD/modeling-app, pull requests merged in 2025-03, with the labels that each got.

#5821 Add modelingWorkflows module with resilient update pattern for adding features
  e2e/playwright/point-click.spec.ts
  e2e/playwright/snapshot-tests.spec.ts-snapshots/Draft-segments-should-look-right-5-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--XZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable--YZ-1-Google-Chrome-linux.png
  e2e/playwright/snapshot-tests.spec.ts-snapshots/extrude-on-default-planes-should-be-stable-YZ-1-Google-Chrome-linux.png
  src/lang/modelingWorkflows.ts
  src/lang/modifyAst/addEdgeTreatment.ts
Labels: bug, dev, desktop-app

#6009 Prevent overwriting the commit status on main
  .github/workflows/update-e2e-branch.yml
Labels: dev

#6011 Set bot user info to amend commits
  .github/workflows/update-e2e-branch.yml
Labels: dev

#6014 Populate all environment variables from files
  .envrc
Labels: dev

#6015 Make tests fail when there are console errors
  .env.development
  e2e/playwright/lib/console-error-whitelist.ts
  e2e/playwright/projects.spec.ts
  e2e/playwright/regression-tests.spec.ts
  e2e/playwright/test-utils.ts
Labels: dev, e2e

#6071 Minor design tweaks to log in page
  src/routes/SignIn.tsx
Labels: design
